/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "inicio.h"
#include <string.h>

#define CREAR_MESA 1
#define UNIRSE_MESA 2

#define IP_NODOMESA "192.168.0.18"
#define IP_ACTUAL "localhost"



void
partida_1(char *host, int opcion, int cantJugadores)
{
	CLIENT *clnt;
	datosMesa  *result;
	datosPartida  crear_mesa_arg;
	datosJugador  unirse_partida_arg;
	int conexionCorrecta=0;

	//logica
	short idMesa;
	short idJugador;

#ifndef	DEBUG
	clnt = clnt_create (IP_NODOMESA, PARTIDA, PRIMER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	switch(opcion){
		case CREAR_MESA:{
			crear_mesa_arg.cantJugadores=cantJugadores;
			//DEBERIA SOLICITAR LA IP DEL EQUIPO..
			sprintf(crear_mesa_arg.ipCreador, "%s",host);

			result = crear_mesa_1(&crear_mesa_arg, clnt);
			if (result == (datosMesa *) NULL) {
				//clnt_perror (clnt, "call failed");
				printf("Error! no se pudo unir a una mesa\n");
			}
			else{
				idMesa= result->idMesa;
				idJugador= result->idJugador;
				printf("El jugador %d creo la mesa:%d\n",idJugador,idMesa);
				conexionCorrecta=1;
			}
		}break;

		case UNIRSE_MESA:{

			//DEBERIA SOLICITAR LA IP DEL EQUIPO..
			sprintf(unirse_partida_arg.ipJugador, "%s",host);

			result = unirse_partida_1(&unirse_partida_arg, clnt);
			if (result == (datosMesa *) NULL) {
				//clnt_perror (clnt, "call failed");
				printf("Error! no se pudo unir a una mesa\n");
			}
			else{
				idMesa= result->idMesa;
				idJugador= result->idJugador;
				if(result->idMesa!=-1){
					printf("se unio el Jugador %d a la mesa: %d\n", idJugador, idMesa);
					conexionCorrecta=1;
				}
					
				else 
					printf("Error! no se pudo unir el jugador a ninguna mesa\n");
			}
		}break;
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

//ejecuto la partida
if(conexionCorrecta){
	char * llamadoServidor = malloc(30);
	sprintf(llamadoServidor, "./DinamicaG_server %d %d", idMesa, idJugador);
	printf("llamo al servidor de juegos\n");
	system(llamadoServidor);
	free(llamadoServidor);
	printf("termino el juego\n");
}

}

void help(char *argv[]){
	printf ("usage: %s IP_JUGADOR OPCION [CANTJUGADORES]\n", argv[0]);
	printf (" OPCION:\n\t1=crearMesa [CANTJUGADORES]\n\t2=unirseMesa ");
	printf ("CANTJUGADORES: 2-3-4\n");
}

int
main (int argc, char *argv[])
{
	char *host;
	int opcion;
	int cantJugadores=0;

	if (argc < 3 | argc>5 ) {
		help(argv);
		exit (1);
	}
	if(argc==3&&(atoi(argv[2])!=2)){
		help(argv);
		exit (1);
	}
		

	host = argv[1];
	opcion= atoi(argv[2]);
	if(opcion==1){
		cantJugadores= atoi(argv[3]);
	}


	partida_1 (host, opcion, cantJugadores);
exit (0);
}
