/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INICIO_H_RPCGEN
#define _INICIO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct datosPartida {
	char ipCreador[20];
	short cantJugadores;
};
typedef struct datosPartida datosPartida;

struct datosJugador {
	char ipJugador[20];
};
typedef struct datosJugador datosJugador;

struct datosMesa {
	short idMesa;
	short cantJugadores;
	short idJugador;
};
typedef struct datosMesa datosMesa;

#define PARTIDA 0x20000008
#define PRIMER 1

#if defined(__STDC__) || defined(__cplusplus)
#define CREAR_MESA 1
extern int noQuedanLugares();
extern  datosMesa * crear_mesa_1(datosPartida *, CLIENT *);
extern  datosMesa * crear_mesa_1_svc(datosPartida *, struct svc_req *);
#define UNIRSE_PARTIDA 2
extern  datosMesa * unirse_partida_1(datosJugador *, CLIENT *);
extern  datosMesa * unirse_partida_1_svc(datosJugador *, struct svc_req *);
extern int partida_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CREAR_MESA 1
extern  datosMesa * crear_mesa_1();
extern  datosMesa * crear_mesa_1_svc();
#define UNIRSE_PARTIDA 2
extern  datosMesa * unirse_partida_1();
extern  datosMesa * unirse_partida_1_svc();
extern int partida_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datosPartida (XDR *, datosPartida*);
extern  bool_t xdr_datosJugador (XDR *, datosJugador*);
extern  bool_t xdr_datosMesa (XDR *, datosMesa*);

#else /* K&R C */
extern bool_t xdr_datosPartida ();
extern bool_t xdr_datosJugador ();
extern bool_t xdr_datosMesa ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INICIO_H_RPCGEN */
