/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "inicio.h"
#include <string.h>


void
partida_1(char *host)
{
	CLIENT *clnt;
	datosMesa  *result_1;
	datosPartida  crear_mesa_1_arg;
	datosMesa  *result_2;
	datosJugador  unirse_partida_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PARTIDA, PRIMER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	//asigno un valor de prueba
	crear_mesa_1_arg.cantJugadores=4;
	//DEBERIA SOLICITAR LA IP DEL EQUIPO..
	sprintf(crear_mesa_1_arg.ipCreador, "%s","192.168.0.1");

	result_2 = unirse_partida_1(&unirse_partida_1_arg, clnt);
				if (result_2 == (datosMesa *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else{
					printf("se unio el Jugador %d a la mesa: %d\n", result_2->idJugador, result_2->idMesa);
				}


	result_1 = crear_mesa_1(&crear_mesa_1_arg, clnt);
	if (result_1 == (datosMesa *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("El jugador %d creo la mesa:%d\n",result_1->idJugador ,result_1->idMesa);
	}


	sprintf(unirse_partida_1_arg.ipJugador, "%s", "192.168.0.5");

	for(int i=0; i<5; i++){
		result_2 = unirse_partida_1(&unirse_partida_1_arg, clnt);
			if (result_2 == (datosMesa *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			else{
				printf("se unio el Jugador %d a la mesa: %d\n", result_2->idJugador, result_2->idMesa);
			}
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	partida_1 (host);
exit (0);
}
