/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "inicio.h"
#include <string.h>

#define CREAR_MESA 1
#define UNIRSE_MESA 2


void
partida_1(char *host, int opcion, int cantJugadores)
{
	CLIENT *clnt;
	datosMesa  *result;
	datosPartida  crear_mesa_arg;
	datosJugador  unirse_partida_arg;
	int conexionCorrecta=0;

#ifndef	DEBUG
	clnt = clnt_create (host, PARTIDA, PRIMER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	switch(opcion){
		case CREAR_MESA:{
			crear_mesa_arg.cantJugadores=cantJugadores;
			//DEBERIA SOLICITAR LA IP DEL EQUIPO..
			sprintf(crear_mesa_arg.ipCreador, "%s","192.168.0.1");

			result = crear_mesa_1(&crear_mesa_arg, clnt);
			if (result == (datosMesa *) NULL) {
				//clnt_perror (clnt, "call failed");
				printf("Error! no se pudo unir a una mesa\n");
			}
			else{
				printf("El jugador %d creo la mesa:%d\n",result->idJugador ,result->idMesa);
				conexionCorrecta=1;
			}
		}break;

		case UNIRSE_MESA:{

			//DEBERIA SOLICITAR LA IP DEL EQUIPO..
			sprintf(unirse_partida_arg.ipJugador, "%s","192.168.0.5");

			result = unirse_partida_1(&unirse_partida_arg, clnt);
			if (result == (datosMesa *) NULL) {
				//clnt_perror (clnt, "call failed");
				printf("Error! no se pudo unir a una mesa\n");
			}
			else{
				if(result->idMesa!=-1){
					printf("se unio el Jugador %d a la mesa: %d\n", result->idJugador, result->idMesa);
					conexionCorrecta=1;
				}
					
				else 
					printf("Error! no se pudo unir el jugador a ninguna mesa\n");
			}
		}break;
	}
	//ACA LLAMAMOS AL SERVER RPC JUGADAS..
	if(conexionCorrecta){
		printf("llamamos al RPC jugadas!\nEsperamos a que comience la partida\n");
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int opcion;
	int cantJugadores=0;

	if (argc < 3 | argc > 5 ) {
		printf ("usage: %s server_host OPCION [CANTJUGADORES]\n", argv[0]);
		printf (" OPCION:\n\t1=crearMesa\n\t2=unirseMesa");
		printf ("CANTJUGADORES: 2-3-4");
		exit (1);
	}

	host = argv[1];
	opcion= atoi(argv[2]);
	if(opcion==1){
		cantJugadores= atoi(argv[3]);
	}


	partida_1 (host, opcion, cantJugadores);
exit (0);
}
