/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "inicio.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

datosMesa *
crear_mesa_1(datosPartida *argp, CLIENT *clnt)
{
	static datosMesa clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CREAR_MESA,
		(xdrproc_t) xdr_datosPartida, (caddr_t) argp,
		(xdrproc_t) xdr_datosMesa, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

datosMesa *
unirse_partida_1(datosJugador *argp, CLIENT *clnt)
{
	static datosMesa clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UNIRSE_PARTIDA,
		(xdrproc_t) xdr_datosJugador, (caddr_t) argp,
		(xdrproc_t) xdr_datosMesa, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
