/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "DinamicaG.h"
#define MAX_JUEGOS 11
#define MAX_JUGADORES_MESA 4
#define CANT_DADOS 5
#define MAX_DADO 6

#define MAX_TIROS 3

//JUEGOS
#define NUM_1 0
#define NUM_2 1
#define NUM_3 2
#define NUM_4 3
#define NUM_5 4
#define NUM_6 5
#define E 6
#define F 7
#define P 8
#define G 9
#define GG 10

short tablaPuntajes[MAX_JUGADORES_MESA][MAX_JUEGOS];
short dadosActuales[5];
short posiblesJuegos[MAX_JUEGOS];
short idJugador;
short idMesa;

//logica
int nroTiro;

//interfaz
char DADOS[6][5][10];

void inicializarDados(){
	//DADO UNO 
	sprintf(DADOS[0][0],"%s","+-------+\0");
	sprintf(DADOS[0][1],"%s","|       |\0");
	sprintf(DADOS[0][2],"%s","|   o   |\0");
	sprintf(DADOS[0][3],"%s","|       |\0");
	sprintf(DADOS[0][4],"%s","+-------+\0");
	//DADO DOS
	sprintf(DADOS[1][0],"%s","+-------+\0");
	sprintf(DADOS[1][1],"%s","|     o |\0");
	sprintf(DADOS[1][2],"%s","|       |\0");
	sprintf(DADOS[1][3],"%s","| o     |\0");
	sprintf(DADOS[1][4],"%s","+-------+\0");
	//DADO TRES
	sprintf(DADOS[2][0],"%s","+-------+\0");
	sprintf(DADOS[2][1],"%s","|     o |\0");
	sprintf(DADOS[2][2],"%s","|   o   |\0");
	sprintf(DADOS[2][3],"%s","| o     |\0");
	sprintf(DADOS[2][4],"%s","+-------+\0");
	//DADO CUATRO
	sprintf(DADOS[3][0],"%s","+-------+\0");
	sprintf(DADOS[3][1],"%s","| o   o |\0");
	sprintf(DADOS[3][2],"%s","|       |\0");
	sprintf(DADOS[3][3],"%s","| o   o |\0");
	sprintf(DADOS[3][4],"%s","+-------+\0");
	//DADO CINCO
	sprintf(DADOS[4][0],"%s","+-------+\0");
	sprintf(DADOS[4][1],"%s","| o   o |\0");
	sprintf(DADOS[4][2],"%s","|   o   |\0");
	sprintf(DADOS[4][3],"%s","| o   o |\0");
	sprintf(DADOS[4][4],"%s","+-------+\0");
	//DADO SEIS
	sprintf(DADOS[5][0],"%s","+-------+\0");
	sprintf(DADOS[5][1],"%s","| o   o |\0");
	sprintf(DADOS[5][2],"%s","| o   o |\0");
	sprintf(DADOS[5][3],"%s","| o   o |\0");
	sprintf(DADOS[5][4],"%s","+-------+\0");
}

void dibujarDados(int d1,int d2, int d3, int d4, int d5){
	for(int i=0; i<5; i++){
		printf("%s  %s  %s  %s  %s\n",DADOS[d1-1][i],DADOS[d2-1][i],DADOS[d3-1][i],DADOS[d4-1][i],DADOS[d5-1][i]);
	}
}

void mostrarDados(){

	printf("\n");
	dibujarDados(dadosActuales[0],dadosActuales[1],dadosActuales[2],dadosActuales[3],dadosActuales[4]);
	
}


void mostrarTablaPuntajes(){
	int puntaje;
	printf("TABLA PUNTAJES TOTAL:\n");
	printf("+-+");
	for(int i=0; i<MAX_JUGADORES_MESA; i++)
		printf("\t+");					//1ra fila
	printf("\n| |");
	for(int i=0; i<MAX_JUGADORES_MESA; i++)
		printf("  %d\t|",i);			//2da fila (idJugador)
	printf("\n+-+");					//3ra fila
	for(int i=0; i<MAX_JUGADORES_MESA; i++)
		printf("\t+");
	printf("\n");					//4ta fila
	

	for(int i=0; i<MAX_DADO; i++){
		
		printf("|%d|", (i+1)); 
		for(int jugador=0; jugador<MAX_JUGADORES_MESA;jugador++){
			puntaje= tablaPuntajes[jugador][i];
			if(puntaje>=0)
				printf("%d\t|", puntaje);
			else if(puntaje==-1) 
				printf("-\t|");
		}
		printf("\n");
	}
	printf("|E|"); 
	for(int jugador=0; jugador<MAX_JUGADORES_MESA; jugador++ ){
		puntaje= tablaPuntajes[jugador][E];
		if(puntaje>=0)
			printf("%d\t|", puntaje);
		else if(puntaje==-1)
			printf("-\t|");
	}
	printf("\n|F|");
	for(int jugador=0; jugador<MAX_JUGADORES_MESA; jugador++ ){
		puntaje= tablaPuntajes[jugador][F];
		if(puntaje>=0)
			printf("%d\t|", puntaje);
		else if(puntaje==-1)
			printf("-\t|");
	}
	printf("\n|P|");
	for(int jugador=0; jugador<MAX_JUGADORES_MESA; jugador++ ){
		puntaje= tablaPuntajes[jugador][P];
		if(puntaje>=0)
			printf("%d\t|", puntaje);
		else if(puntaje==-1)
			printf("-\t|");
	}
	printf("\n|G|");
	for(int jugador=0; jugador<MAX_JUGADORES_MESA; jugador++ ){
		puntaje= tablaPuntajes[jugador][G];
		if(puntaje>=0)
			printf("%d\t|", puntaje);
		else if(puntaje==-1)
			printf("-\t|");
	}
	printf("\n|H|");
	for(int jugador=0; jugador<MAX_JUGADORES_MESA; jugador++ ){
		puntaje= tablaPuntajes[jugador][GG];
		if(puntaje>=0)
			printf("%d\t|", puntaje);
		else if(puntaje==-1)
		printf("-\t|");
	}
	printf("\n|T|");
	int totales[MAX_JUGADORES_MESA];
	for(int i=0; i<MAX_JUGADORES_MESA; i++)
		totales[i]=0;

	for(int jugador=0; jugador<MAX_JUGADORES_MESA; jugador++)
		for(int i=0; i<MAX_JUEGOS; i++)
			if(tablaPuntajes[jugador][i]>=0)
				totales[jugador]= totales[jugador] + tablaPuntajes[jugador][i];

	for(int jugador=0; jugador<MAX_JUGADORES_MESA; jugador++ ){
		if(totales[jugador]>=0)
			printf("%d\t|", totales[jugador]);
		else if(totales[jugador]==-1)
		printf("-\t|");
	}

	printf("\n");
	printf("------------------------------------------\n");
}

void mostrarJuegosPosibles(){
	int valorPosible;
	printf("Posibles Juegos:\n");
	for(int i=0; i<MAX_DADO; i++){
		valorPosible= posiblesJuegos[i];
		if(valorPosible>0)
			printf("%d: %d\n", (i+1), valorPosible);
	}
	valorPosible= posiblesJuegos[E];
	if(valorPosible>0)
		printf("E: %d\n", valorPosible);

	valorPosible= posiblesJuegos[F];
	if(valorPosible>0)
		printf("F: %d\n", valorPosible);

	valorPosible= posiblesJuegos[P];
	if(valorPosible>0)
		printf("P: %d\n", valorPosible);

	valorPosible= posiblesJuegos[G];
	if(valorPosible>0)
		printf("G: %d\n", valorPosible);

	valorPosible= posiblesJuegos[GG];
	if(valorPosible>0)
		printf("GG: %d\n", valorPosible);

	printf("--------------\n");
}

void juegosPosibles(){
	int contadorNros[MAX_DADO]; //arreglos que cuentan cuantos apariciones de cada numero hay.
	
	for(int i=0; i<CANT_DADOS;i++)
		contadorNros[i]=0;

	//cuento las apariciones de cada uno de los nros entre los 5 dados.
	for(int i=0; i<CANT_DADOS;i++){
		int valorDado= dadosActuales[i];
		contadorNros[valorDado-1]++;
	}

	//busco GENERALA
	int pos=0;
	while(pos<MAX_DADO)
		if(contadorNros[pos]==5){
			posiblesJuegos[G]=50;
			break;
		}
		else pos++;

	if(pos==MAX_DADO)
		posiblesJuegos[G]=0;

	//busco POKER
	pos=0;
	while(pos<MAX_DADO)
		if(contadorNros[pos]>=4){
			posiblesJuegos[P]=40;
			break;
		}
		else pos++;
	if(pos==MAX_DADO)
		posiblesJuegos[P]=0;

	//busco Full
	pos=0;
	int hayTres=0;
	int hayDos=0;
	while(pos<MAX_DADO){
		if(contadorNros[pos]==2)
			hayDos=1;
		if(contadorNros[pos]==3)
			hayTres=1;
		pos++;
	}
	if(hayDos && hayTres)
		posiblesJuegos[F]=30;
	else
		posiblesJuegos[F]=0;

	//busco ESCALERA
	int cantSeguidos=0;
	for(int i=0; i<MAX_DADO; i++){
		if(contadorNros[i]>0){
			cantSeguidos++;
			if(cantSeguidos==5)
				break;
		}

		else cantSeguidos=0;
	}
	if(cantSeguidos==5)
		posiblesJuegos[E]=20;
	else 
		posiblesJuegos[E]=0;

	//busco Juegos de Nros (1,2,3,4,5,6)
	for(int i=0; i<MAX_DADO; i++){
		posiblesJuegos[i]=contadorNros[i]*(i+1);
	}
}

int obtenerNroJuego(char letra){
	int nroJuego= atoi(&letra);
	nroJuego=nroJuego-1;
	if(nroJuego==-1){
		if(letra=='E')
			nroJuego=E;
		if(letra=='F')
			nroJuego=F;
		if(letra=='P')
			nroJuego=P;
		if(letra=='G')
			nroJuego=G;
		if(letra=='H')
			nroJuego=GG;
	}
	return nroJuego;
}

char anotarJugada(){
	char charJuego;
	int nroJuego;
	int seAnoto=0;
	while(!seAnoto){
		printf("ingrese el juego a anotar:\n");
		scanf(" %c",&charJuego);
		//casteo de char a entero
		nroJuego=obtenerNroJuego(charJuego);
		//chequear si el juego a anotar es valido:
		if(tablaPuntajes[idJugador][nroJuego]==-1 && posiblesJuegos[nroJuego]>0){
			tablaPuntajes[idJugador][nroJuego]=posiblesJuegos[nroJuego];
			printf("se agrego correctamente el juego a la tabla de puntajes.\n");
			mostrarTablaPuntajes(idJugador);
			printf("anoté: %c\n", charJuego);
			seAnoto=1;
		}
		else printf("Error! no puede anotar dicho juego.\n");
	}
	return charJuego;
}

posDados *
tirar_dados_1_svc(struct dados *argp, struct svc_req *rqstp)
{
	system("clear");
	static posDados  result;
	printf("\t\tTURNO: %d\n",nroTiro);
	//recibo los dados aleatorios del servidorMesas,
	//verifico si son para mi
	if(idMesa==argp->idMesa){
		//verifico que los dados son para este jugador
		if(idJugador==argp->idJugador){
			//muestro los dados recibidos por pantalla..

			//actualizar dados..
			for(int i=0; i<CANT_DADOS; i++)
				dadosActuales[i]= argp->dados[i];
				
			mostrarDados();
			juegosPosibles();
			mostrarTablaPuntajes(idJugador);
			mostrarJuegosPosibles();

			//EL CLIENTE ELIGE SI ANOTAR O VOLVER A TIRAR (DADOS ESPECIFICOS)
			int opcionValida=0;
			char opcion;
			while(!opcionValida){
				printf("¿Desea anotar [a] o volver a tirar [t]?\n");
				scanf(" %c",&opcion);
				if(opcion=='a'||opcion=='t')
					opcionValida=1;
				if(nroTiro==MAX_TIROS && opcion=='t'){
					printf("Ya no tiene mas tiros!\n");
					opcionValida=0;
				}
			}

			//si ingreso ANOTAR:
			if(opcion=='a'){
					result.tipoJugada = anotarJugada();
					nroTiro=1;
			}
			else if(opcion=='t'){		//si ingreso VOLVER A TIRAR:
				nroTiro++;

				printf("ingrese la cantidad a volver a tirar\n");
				int cantidad=0;
				scanf(" %d",&cantidad);
				int dadoNro;
				printf("ingrese las posiciones (1-5):\n");
				for(int i=0; i<CANT_DADOS; i++)
					result.pos[i]=0;
				for(int i=0; i<cantidad;i++){
					scanf(" %d",&dadoNro);
					result.pos[dadoNro-1]=1;
				}
				result.tipoJugada='T';
			}
		}
		else{
			printf("Error! el msje es para otro jugador.\n");
		}
	}
	else{
		printf("Error! el msje es para otra mesa.\n");
	}
	return &result;
}

short *
actualizar_dados_1_svc(struct dados *argp, struct svc_req *rqstp)
{
	static short  result=0;
	if(idMesa==argp->idMesa){
		//verifico que no me llegaron los dados que yo tire
		if(idJugador!=argp->idJugador){
			//actualizar dados..
			for(int i=0; i<CANT_DADOS; i++)
				dadosActuales[i]= argp->dados[i];
			
			
			if(nroTiro==1){
				system("clear");
				printf("\t\tTURNO JUGADOR %d\n",argp->idJugador);	
				mostrarTablaPuntajes();
			}	
			printf("\tTIRO N° %d\n",nroTiro);
			mostrarDados();
			nroTiro++;
			//como fue satisfatorio contesto OK
			result= 1;
		}
		else
			printf("Error! Yo tire los dados!\n");	//respondo 0
	}
	else 
		printf("Error! el msje es para otra mesa\n");			//respondo 0
	return &result;
}

short *
actualizar_tabla_1_svc(struct informacionMesa *argp, struct svc_req *rqstp)
{
	static short  result;
	//recibo la informacion del jugador a actualizar..
	if(idMesa==argp->idMesa){

		short jugadorQueAnoto = argp->idJugador;
		//verifico que los datos NO son de este jugador.
		if(idJugador!=jugadorQueAnoto){
			short puntajeAnotado= argp->puntajeJugada;
			char tipoJugadaQueAnoto= argp->tipoJugada;
			int nroJugada= obtenerNroJuego(tipoJugadaQueAnoto);

			//anotamos el puntaje en la celda correspondiente
			tablaPuntajes[jugadorQueAnoto][nroJugada]= puntajeAnotado;
//			printf("Se anoto %dpts. en el juego %d la tabla de puntajes de %d..\n", puntajeAnotado, nroJugada, jugadorQueAnoto);
//			mostrarTablaPuntajes(jugadorQueAnoto);
			nroTiro=1;
		}
		else 
			printf("Error! esta jugada es mia!\n");
	}
	else 
		printf("Error! este puntaje es de otra mesa\n");


	return &result;
}

void AlIniciar(short idMesaRecibida, short idJugadorRecibido){
	inicializarDados();
	printf("arranque!\n");
	//inicializo el idJugador y idMesa
	idMesa=idMesaRecibida;
	idJugador= idJugadorRecibido;
	nroTiro=1;
	//incializo los valores de todos los puntajes en -1 (representa que no se anoto nada todav)
	for(int jug=0; jug<MAX_JUGADORES_MESA; jug++)
		for(int p=0; p<MAX_JUEGOS; p++)
			tablaPuntajes[jug][p]=-1;
	printf("..termine de cargar los puntajes iniciales\n");
}
