/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "DinamicaG.h"
#include <stdlib.h>
//random
#include <time.h>

#define MAX_JUEGOS 11
#define MAX_JUGADORES_MESA 4
#define TAMANO_IP 20

//LOGICA
#define MAX_DADO 6
#define CANT_DADOS 5

//variables globales
short tablaPuntajes[MAX_JUGADORES_MESA][MAX_JUEGOS];
char ipJugadores[MAX_JUGADORES_MESA][TAMANO_IP];
short cantJugadoresMesa;
short posDadosVolverATirar[CANT_DADOS];
short idMesa;
int turnoActual;


int tirarDado(){
	//se obtiene un numero entre 1 y 6
	   // should only be called once
	return (rand()%6)+1;
}

int obtenerPuntajeJugada(char tipoJugada, int turnoActual, short dados[]){
	int puntajeJugada=0;

	if(tipoJugada>='1'&&tipoJugada<='6'){	
		int Nro= atoi(&tipoJugada);	//juegos con Nros
		for(int i=0; i<CANT_DADOS; i++){
			if(dados[i]==Nro)
				puntajeJugada+=Nro;
		}
			
	}
	else{										//juagadas especiales
		if(tipoJugada=='E')
			puntajeJugada=20;
		else if (tipoJugada=='F')
			puntajeJugada=30;
		else if (tipoJugada=='P')
			puntajeJugada=40;
		else if (tipoJugada=='G')
			puntajeJugada=50;
		else if (tipoJugada=='H')
			puntajeJugada= 100;

		if(turnoActual==1){			//servido
			puntajeJugada+=5;
		}
	}
	return puntajeJugada;
}

int
comenzarTurnoJugador(short idJugadorActual)
{
	CLIENT *clnt;
	posDados  *result_posDados;
	struct dados  tirar_dados_arg;
	short  *result_2;
	struct dados  actualizar_dados_arg;
	short  *result_3;
	struct informacionMesa  actualizar_tabla_arg;
	
	char* host= ipJugadores[idJugadorActual];
	//para la logica de los turnos..
	int quiereAnotar;
	int puntajeJugadaActual;
	char tipoJugadaActual;
	short dados[CANT_DADOS];

	//seteo valores por defecto..
	tirar_dados_arg.idJugador=idJugadorActual;
	tirar_dados_arg.idMesa= idMesa;
	quiereAnotar=0;

//SETEO LOS DADOS A ENVIAR..
for(int i=0; i<CANT_DADOS; i++)
	printf("%d, ",dados[i]);

printf("\n");
for(int i=0; i<CANT_DADOS; i++){
	if(posDadosVolverATirar[i]==1){
		dados[i]=tirarDado();
	}
	printf("%d, ",dados[i]);
}

//ENVIO AL RESTO LOS DADOS PARA QUE LOS ACTUALICEN
for(int i=0; i<CANT_DADOS; i++){
	actualizar_dados_arg.dados[i]=dados[i];
	tirar_dados_arg.dados[i]=dados[i];
}
//actualizo data de paquetes:
actualizar_dados_arg.idJugador= idJugadorActual;
actualizar_dados_arg.idMesa= idMesa;
tirar_dados_arg.idJugador= idJugadorActual;
tirar_dados_arg.idMesa= idMesa;
for(int i=0; i<cantJugadoresMesa; i++){
	
	//seteo la comunicacion con cada uno de los jugadores..
	host= ipJugadores[i];
	if(i!=idJugadorActual){	//no es el jugador actual
		
		#ifndef	DEBUG
			clnt = clnt_create (host, JUGADA, PRIMERA, "tcp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}
		#endif	/* DEBUG */
		result_2 = actualizar_dados_1(&actualizar_dados_arg, clnt);
		if (result_2 == (short *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else{
			if(*result_2==1)
				printf("jugador %d actualizo dados correctamente\n", i);
			else 
				printf("Error! jugador %d no actualizo dados\n",i );
		}
		#ifndef	DEBUG
			clnt_destroy (clnt);
		#endif	 /* DEBUG */	
	}

}

//SI ES EL JUGADOR ACTUAL..
//seteo la comunicacion con cada uno de los jugadores..
host= ipJugadores[idJugadorActual];
#ifndef	DEBUG
	clnt = clnt_create (host, JUGADA, PRIMERA, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

result_posDados = tirar_dados_1(&tirar_dados_arg, clnt);
if (result_posDados == (posDados *) NULL) {
	clnt_perror (clnt, "call failed");
}
else{
	if(result_posDados->tipoJugada!='T'){	//quiere anotar
		printf("Quiere anotar\n");
		quiereAnotar=1;
	}
	else {
		printf("Quiere volver a tirar\n");
		for(int i=0; i<CANT_DADOS; i++){
			posDadosVolverATirar[i]= result_posDados->pos[i];
			printf("%d,", posDadosVolverATirar[i]);
		}
			
	}
}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

//EN CASO QUE QUIERA ANOTAR..
if(quiereAnotar){
	//determino que valor quiere anotar..,
	tipoJugadaActual= result_posDados->tipoJugada;
	puntajeJugadaActual= obtenerPuntajeJugada(tipoJugadaActual, turnoActual, tirar_dados_arg.dados);
	printf("El jugador %d anoto %d al %c\n", idJugadorActual, puntajeJugadaActual, tipoJugadaActual);

	//enviamos el puntaje de la jugada para que todos anoten dicho valor..
	actualizar_tabla_arg.idJugador=idJugadorActual;
	actualizar_tabla_arg.idMesa=idMesa;
	actualizar_tabla_arg.puntajeJugada=puntajeJugadaActual;
	actualizar_tabla_arg.tipoJugada= tipoJugadaActual;

	for(int i=0; i<cantJugadoresMesa; i++){
		//seteo la comunicacion con cada uno de los jugadores..
		if(i!=idJugadorActual){	//no es el jugador actual
			host= ipJugadores[i];
			
			#ifndef	DEBUG
			clnt = clnt_create (host, JUGADA, PRIMERA, "tcp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}
			#endif	/* DEBUG */

			result_3 = actualizar_tabla_1(&actualizar_tabla_arg, clnt);
			if (result_3 == (short *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			else{
				if(*result_3==1)
					printf("jugador %d actualizo su tabla correctamente\n", i);
				else 
					printf("Error! jugador %d no actualizo tabla\n",i );
			}
			#ifndef	DEBUG
			clnt_destroy (clnt);
			#endif	 /* DEBUG */
		}
	}
}

return quiereAnotar;
//FIN ENVIO DADOS JUGADOR ACTUAL
}

int
main (int argc, char *argv[])
{
	//genero la semilla para obtener los dados segun la hora.
	srand(time(NULL));

	//recibo por parametro el idMesa y mi nro de jugador en dicha mesa..
	if (argc < 2) {
		printf ("usage: %s ID_Mesa\n", argv[0]);
		exit (1);
	}
	idMesa= atoi(argv[1]);
	
	//inicializo ipJugadores con los valores dentro del archivo "ipJugadores.txt"
	FILE *f;
	f= fopen("jugadoresIPs.txt", "r");
	cantJugadoresMesa=0;
    while (fscanf(f, " %20s", ipJugadores[cantJugadoresMesa]) == 1) {
		cantJugadoresMesa++;
    }
	printf("cant jugadores: %d\n", cantJugadoresMesa);
	for(int i=0; i<cantJugadoresMesa; i++){
		printf("id %d: %s\n", i, ipJugadores[i]);
	}

	//incializo los valores de todos los puntajes en -1 (representa que no se anoto nada todav)
	for(int jug=0; jug<MAX_JUGADORES_MESA; jug++)
		for(int p=0; p<MAX_JUEGOS; p++)
			tablaPuntajes[jug][p]=-1;
	
	//una vez que ya esta todo inicializado..
	//ARRANCA EL JUEGO!!
	//esto deberia repetirse 11 veces para cada jugador..
	

	//le doy un turno a cada uno de los jugadores
	for(int ronda=1; ronda<=MAX_JUEGOS; ronda++){
		printf("\n\t\tRONDA %d\n", ronda);
		for(int i=0; i<cantJugadoresMesa; i++){
			//turno de jugadorActual
			printf("\tTurno de jugador %d\n", i);
			int anoto=0;
			turnoActual=1;
			while(!anoto&& turnoActual<=3){
				if(turnoActual==1){
					for(int i=0; i<CANT_DADOS; i++)
						posDadosVolverATirar[i]=1;
				}
				anoto=	comenzarTurnoJugador(i);
				turnoActual++;
			//una vez que anota le pasa el turno al siguiente jugador
			}
		}
	}
	
/*	short dados[CANT_DADOS];
	for(int i=0; i<CANT_DADOS; i++){
		dados[i]=i+1;
	}

	enviarTirarDado(dados, 0);	
*/
	exit (0);
}