/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "DinamicaG.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

posDados *
tirar_dados_1(struct dados *argp, CLIENT *clnt)
{
	static posDados clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, TIRAR_DADOS,
		(xdrproc_t) xdr_dados, (caddr_t) argp,
		(xdrproc_t) xdr_posDados, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

short *
actualizar_dados_1(struct dados *argp, CLIENT *clnt)
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ACTUALIZAR_DADOS,
		(xdrproc_t) xdr_dados, (caddr_t) argp,
		(xdrproc_t) xdr_short, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

short *
actualizar_tabla_1(struct informacionMesa *argp, CLIENT *clnt)
{
	static short clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ACTUALIZAR_TABLA,
		(xdrproc_t) xdr_informacionMesa, (caddr_t) argp,
		(xdrproc_t) xdr_short, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
